Models/ErrorViewModel.cs
using System;

namespace Property_Rental.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Property.cs
namespace PropertyRental.Models{
    public class Property {

        public int Id {get; set;}

        public string Name {get; set;}
        
        public int Rooms {get; set;}

        public decimal BathRooms {get; set;}

        public decimal Price {get; set;}

        public int SqrFeet {get; set;}

        public string ImageUrl {get; set;}

        public string Description {get; set;}
   }

}

Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using PropertyRental.Models;

namespace PropertyRental.Controllers{

    public class CatalogController : Controller {

        public IActionResult Test(){
            return View();
        }
        public IActionResult Index(){
            return View();
        }
        public IActionResult Register(){
            return View();
        }
        // catalog/register property
        [HttpPost]

        public IActionResult RegisterProperty([FromBody] Property p){
            System.Console.WriteLine("user is saving something");

            // save p on database

            return Json(p);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Property_Rental.Models;

namespace Property_Rental.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
    public IActionResult Test(){
        return View();
    }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Catalog/Index.cshtml


<h2 style="color:blue">Our Amazing Catalog</h2>

<div id="catalogContainer">
    Rendering Catalog Here
</div>


@section Scripts {
    <script src="/js/catalog.js"></script>
}

Views/Catalog/Register.cshtml
@{
    ViewData["Title"]= "Register Property";
}


<form>
   
<h2 style="color: teal;">Register</h2>
   
  <div class="form-group">
    <label for="exampleFormControlInput1">Name</label>
    <input type="text" class="form-control" id="name" placeholder="name">
  </div>

  <div class="form-group">
    <label for="exampleFormControlSelect1">Rooms</label>
    <select class="form-control" type= "number" id="rooms">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>
  </div>

  <div class="form-group">
    <label for="exampleFormControlSelect2">Bathroom</label>
    <select class="form-control" id="bathroom">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>
  </div>

   <div class="form-group">
    <label for="exampleFormControlTextarea1">Price</label>
    <input type="number" class="form-control" id="price" placeholder="price">
  
  </div>

  <div class="form-group">
    <label for="exampleFormControlTextarea1">Square Feet</label>
    <input type="number" class="form-control" id="SqrFeet" placeholder="square feet">
  
  </div>

  <div class="form-group">
    <label for="exampleFormControlTextarea1">Image name:</label>
    <textarea class="form-control" id="image" rows="1"></textarea>
  </div>

  <div class="form-group">
    <label for="exampleFormControlTextarea1">Description</label>
    <textarea class="form-control" id="description" type=" text" rows="3"></textarea>
  </div>

  <div class="form-group row">
      <div >
      <button type="button" id="btnSave" class="btn btn-info">Register</button>
      </div>
  </div>
</form>

@section Scripts {
    <script src="/js/register.js"></script>
}

Views/Catalog/Test.cshtml


<h2 style="color:purple">This is another test page</h2>

Views/Home/About.cshtml
@{
    ViewData["Title"]= "About me";
}

<h2 style="color: aquamarine;"><i>Terri M Woods</i></h2>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/Test.cshtml


<h2 style="color:violet">This is a test</h2> 

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Property_Rental</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Property_Rental</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Index">Catalog</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Register">Admin</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Property_Rental - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>